cad: []
description: Off-the-shelf, cheap, snap opening drag chain for gantry wiring and protecting
  wires down to the deck
images: []
mod_version: 1
printer_compatibility:
- V2.1
title: Openbuilds Drag Chain 2.1
