cad:
- STEPs/v0_920_mount.STEP
- STEPs/Cable_Clip_Tophat_x2.STEP
- STEPs/Cable_Clip_Tophat_Corner_x2.STEP
description: Mounting bracket for a Logitech C920 on the tophat
images:
- Images/Mount.jpg
- Images/From_Above.jpg
- Images/Cable_Routing.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: V0 C920 Tophat Mount
