cad:
- triangle_lab_filament_sensor_mount.f3d
- triangle_lab_filament_sensor_mount.step
description: Triange Lab filament sensor mounts
images:
- triangle_lab_filament_sensor_mount.jpeg
- triangle_lab_filament_sensor_mount_small.jpeg
mod_version: 1
printer_compatibility:
- V2.2
title: Triangle Lab Filament Sensor Mount
