cad:
- 5v_psupply_mount.f3d
- bed_extrusion_spacer_parametric.f3d
- dial_indicator_fan_mount.f3d
- FSR_circuit_mount.f3d
- mains_plug_panel-parametric.f3d
- z_rail_stop_PARAMETRIC_x4.f3d
description: An extra tab added to the Z idler to prevent sagging / rotation
images: []
mod_version: 1
printer_compatibility:
- V2.1
title: Z Idler Frame Extra Tab
