cad:
- CAD/Revo_Nozzle_v12.step
description: A skirt case for the Revo hotends to reside R1 and R2
images:
- Images/Finished_Open.jpg
- Images/Open.png
- Images/Finished_Closed.jpg
- Images/Completed.png
- Images/AllSizes.png
mod_version: 1
printer_compatibility:
- V2.4
title: Revo hotend skirt case
